[workspace]
members = [
    "plerkle", # 1.6.0+solana.1.17.5
    "plerkle_messenger", # 1.6.8
    "plerkle_serialization", # 1.6.0+solana.1.17.5
]

[profile.release]
debug = true
lto = true
codegen-units = 1
