[workspace]
resolver = "2"
members = [
    "plerkle", # 1.6.0+solana.2.0.5
    "plerkle_messenger", # 1.6.6
    "plerkle_serialization", # 1.6.0+solana.2.0.5
]

[profile.release]
lto = true
codegen-units = 1
