[workspace]
members = [
    "plerkle", # 1.6.0+solana.1.17.20
    "plerkle_messenger", # 1.6.6
    "plerkle_serialization", # 1.6.0+solana.1.17.20
]

[profile.release]
debug = true
lto = true
codegen-units = 1
