concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ["${{ matrix.os }}"]

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true

    - name: set env vars
      run: |
        source ci/env.sh
        echo "RUST_VERSION=$rust_version" | tee -a "$GITHUB_ENV"
        echo "RUST_PROFILE=$rust_profile" | tee -a "$GITHUB_ENV"
        echo "RUST_COMPONENTS=$rust_components" | tee -a "$GITHUB_ENV"

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ env.RUST_VERSION }}
        components: clippy

    - name: Run clippy
      run: cargo clippy --all-targets --tests -- -Dwarnings

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: -- --nocapture

    - name: Build plerkle plugin
      run: cargo build --verbose --release
